name: MiyagiAI
summary: This is a deployment of a Miyagi  AI environment 
description: deploys a Miyagi AI environment
templatePath: main.bicep
parameters:
- id: "location"
  name: "Location"
  description: "Location to deploy the environment resources. If not specified, will deploy to the region of the project"
  type: "string"
  default: "eastus"
- id: "searchServices_miyagikrystaldevboxdev_acs_1_name"
  name: "Search Service Name"
  description: "Name of the Cognitive Search service"
  type: "string"
- id: "service_miyagikrystaldevboxdev_apim_1_name"
  name: "API Management Name"
  description: "Name of the API Management instance"
  type: "string"
- id: "namespaces_miyagikrystaldevboxdev_evhns_1_name"
  name: "Event Hub Namespace Name"
  description: "Name of the Event Hub namespace"
  type: "string"
- id: "eventHubName"
  name: "Event Hub Name"
  description: "Name of the Event Hub"
  type: "string"
- id: "storageAccounts_miyagikrystaldevboxdevbl_name"
  name: "Storage Account Name"
  description: "Name of the Storage Account"
  type: "string"
- id: "databaseAccounts_miyagikrystaldevboxdev_cosmos_1_name"
  name: "Cosmos DB Account Name"
  description: "Name of the Cosmos DB Account"
  type: "string"
- id: "accounts_miyagikrystaldevboxdev_OpenAIService_1_name"
  name: "OpenAI Service Account Name"
  description: "Name of the OpenAI Service Account"
  type: "string"
- id: "registries_miyagikrystaldevboxdevacr1oouicaqdhvltg_name"
  name: "Container Registry Name"
  description: "Name of the Container Registry"
  type: "string"
runner: Bicep