name: Miyagi-Environment-Api-eventhub
summary: This is an Miyagi-Environment Dev.
description: Deploys all Miyagi for Developers.
templatePath: main.bicep
parameters:
  - id: "location"
    name: "Location"
    description: "Location to deploy the environment resources. If not specified, will deploy to the region of the project"
    type: "string"
    default: "Central US"

  - id: "searchServiceName"
    name: "Search Service Name"
    description: "Name of the Cognitive Search service"
    type: "string"

  - id: "apiManagementName"
    name: "API Management Name"
    description: "Name of the API Management instance"
    type: "string"

  - id: "eventHubNamespaceName"
    name: "Event Hub Namespace Name"
    description: "Name of the Event Hub namespace"
    type: "string"

  - id: "eventHubName"
    name: "Event Hub Name"
    description: "Name of the Event Hub"
    type: "string"
runner: bicep